import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  base: '/',
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // Use the existing manifest.json from the public folder
      manifest: false, 
      workbox: {
        // Precache assets generated by the build, including local fonts for better offline reliability.
        globPatterns: ['**/*.{js,css,html,ico,png,svg,json,ttf,otf}'],
        // Add runtime caching for remote fonts (e.g., Google Fonts).
        runtimeCaching: [],
      },
    }),
  ],
});